# Generated by Django 5.0.3 on 2025-05-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=255, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('tipe', models.CharField(choices=[('G', 'General'), ('D', 'Detail')])),
                ('level', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)])),
                ('induk', models.CharField(blank=True, max_length=255, null=True)),
                ('satuan', models.CharField(blank=True, max_length=255, null=True)),
                ('harga', models.IntegerField(blank=True, null=True)),
                ('qtystok', models.IntegerField()),
            ],
        ),
    ]
