# Generated by Django 5.0.3 on 2025-05-07 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0002_alter_masterbarang_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterbarang',
            name='induk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='barang.masterbarang'),
        ),
    ]
