# Generated by Django 5.0.3 on 2025-05-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0003_alter_masterbarang_induk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterbarang',
            name='qtystok',
            field=models.IntegerField(default=0),
        ),
    ]
