# Generated by Django 5.0.3 on 2025-05-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0004_alter_masterbarang_qtystok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterbarang',
            name='qtystok',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
