# Generated by Django 5.0.3 on 2025-05-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TerimaBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_terima', models.CharField(max_length=255, unique=True)),
                ('tanggal', models.DateField()),
                ('pemasok', models.CharField(max_length=255)),
                ('gudang', models.CharField(max_length=255)),
                ('nomor_po', models.CharField(max_length=255)),
                ('kode_barang', models.CharField(max_length=255)),
                ('QtyTerima', models.IntegerField()),
            ],
        ),
    ]
