# Generated by Django 5.0.3 on 2025-05-06 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preorder', '0002_preorder_harga_preorder_qty_terima'),
        ('terima_barang', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terimabarang',
            name='gudang',
        ),
        migrations.RemoveField(
            model_name='terimabarang',
            name='nomor_po',
        ),
        migrations.AlterField(
            model_name='terimabarang',
            name='pemasok',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preorder', to='preorder.preorder'),
        ),
    ]
