# Generated by Django 5.0.3 on 2025-05-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terima_barang', '0002_remove_terimabarang_gudang_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terimabarang',
            old_name='QtyTerima',
            new_name='qty_terima',
        ),
    ]
