# Generated by Django 5.0.3 on 2025-05-12 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terima_barang', '0003_rename_qtyterima_terimabarang_qty_terima'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terimabarang',
            old_name='pemasok',
            new_name='preorder',
        ),
    ]
