# Generated by Django 5.0.3 on 2025-05-13 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0005_alter_masterbarang_qtystok'),
        ('terima_barang', '0004_rename_pemasok_terimabarang_preorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terimabarang',
            name='kode_barang',
        ),
        migrations.RemoveField(
            model_name='terimabarang',
            name='qty_terima',
        ),
        migrations.CreateModel(
            name='TerimaBarangDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_terima', models.IntegerField()),
                ('kode_barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barang.masterbarang')),
                ('terima_barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terima_barang_detail', to='terima_barang.terimabarang')),
            ],
        ),
    ]
