# Generated by Django 5.0.3 on 2025-05-06 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_mastergudang'),
        ('barang', '0001_initial'),
        ('gudang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_po', models.CharField(max_length=255, unique=True)),
                ('tanggal', models.DateField()),
                ('QtyPO', models.IntegerField()),
                ('gudang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gudang.mastergudang')),
                ('kode_barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barang.masterbarang')),
                ('pemasok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.masterpemasok')),
            ],
        ),
    ]
