# Generated by Django 5.0.3 on 2025-05-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='harga',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preorder',
            name='qty_terima',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
