# Generated by Django 5.0.3 on 2025-05-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preorder', '0002_preorder_harga_preorder_qty_terima'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preorder',
            old_name='QtyPO',
            new_name='qty_po',
        ),
        migrations.AlterField(
            model_name='preorder',
            name='qty_terima',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
