# Generated by Django 5.0.3 on 2025-05-13 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0005_alter_masterbarang_qtystok'),
        ('preorder', '0003_rename_qtypo_preorder_qty_po_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorder',
            name='harga',
        ),
        migrations.RemoveField(
            model_name='preorder',
            name='kode_barang',
        ),
        migrations.RemoveField(
            model_name='preorder',
            name='qty_po',
        ),
        migrations.RemoveField(
            model_name='preorder',
            name='qty_terima',
        ),
        migrations.CreateModel(
            name='PreOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_po', models.IntegerField()),
                ('harga', models.IntegerField()),
                ('qty_terima', models.IntegerField(blank=True, null=True)),
                ('kode_barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barang.masterbarang')),
                ('preorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preorder_detail', to='preorder.preorder')),
            ],
        ),
    ]
