# Generated by Django 5.0.3 on 2025-05-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preorder', '0004_remove_preorder_harga_remove_preorder_kode_barang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorderdetail',
            name='qty_terima',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
