# Generated by Django 5.0.3 on 2025-05-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterGudang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=255, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('alamat', models.TextField()),
            ],
        ),
    ]
